import {loadRepoData} from './data.js';
import {checkApi} from './api.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DRAFT_KEY='kursy.routes.draft.v2';
const DEFAULT_LOCATION='Centrum Zielonej Góry, Zielona Góra';
const HOURS=Array.from({length:24},(_,i)=>String(i).padStart(2,'0'));
const MINUTES=Array.from({length:60},(_,i)=>String(i).padStart(2,'0'));
let state={company:null,routes:[],repoRoutes:[],courses:[]};
let editor=null;
let timeTarget=null;
let stopEditorId=null;
let deferredInstallPrompt=null;

const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=v=>JSON.parse(JSON.stringify(v));
const makeId=(p='id')=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const normalizeTime=v=>/^\d{2}:\d{2}$/.test(v||'')?v:'00:00';

function normalizeStop(s={}){const out=s.locationOut||s.location||s.coordinates||DEFAULT_LOCATION;return {id:s.id||makeId('stop'),name:s.name||'',locationOut:out,locationReturn:s.locationReturn||s.returnLocation||out,times:{...(s.times||{})}}}
function normalizeRoute(r={}){return {id:r.id||makeId('route'),name:r.name||'',description:r.description||'',services:(r.services||[]).map(s=>({id:s.id||makeId('service'),targetTime:normalizeTime(s.targetTime||'06:00')})),stops:(r.stops||[]).map(normalizeStop)}}
function readDraft(){try{const p=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');const routes=Array.isArray(p)?p:Array.isArray(p?.routes)?p.routes:null;return routes?routes.map(normalizeRoute):null}catch{return null}}
function writeDraft(){localStorage.setItem(DRAFT_KEY,JSON.stringify(state.routes));$('#draftNotice').hidden=false;$('#dataStatus').textContent='Wersja robocza'}
function show(view){$$('.view').forEach(v=>v.hidden=v.id!==`view-${view}`);$$('.nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#pageTitle').textContent={home:'Strona główna',routes:'Moje trasy',admin:'Administracja',driver:'Tryb kierowcy'}[view]||'Kursy'}
function renderHome(){$('#companyName').textContent=state.company?.name||'—';$('#routesCount').textContent=state.routes.length;$('#coursesCount').textContent=state.routes.reduce((n,r)=>n+(r.services?.length||0),0)}
function renderRoutes(){const box=$('#routesList');if(!state.routes.length){box.innerHTML='<div class="empty">Nie ma jeszcze żadnej trasy. Kliknij „Dodaj trasę”.</div>';return}box.innerHTML=state.routes.map(r=>`<div class="item"><div><strong>${esc(r.name)}</strong><br><small>${r.stops.length} przystanków • ${r.services.length} kursów • ${esc(r.description||'Bez opisu')}</small></div><div class="itemActions"><button class="btn" data-edit-route="${esc(r.id)}">Edytuj</button><button class="btn dangerText" data-delete-route="${esc(r.id)}">Usuń</button></div></div>`).join('')}
function renderAll(){renderHome();renderRoutes()}
function stopById(id){return editor?.stops.find(s=>s.id===id)}

function openEditor(routeId=null){const src=routeId?state.routes.find(r=>r.id===routeId):null;editor=src?clone(src):normalizeRoute({services:[{id:makeId('service'),targetTime:'06:00'}],stops:[normalizeStop({})]});editor.stops=editor.stops.length?editor.stops:[normalizeStop({})];$('#routeEditor').hidden=false;renderEditor();$('#routeEditor').scrollIntoView({behavior:'smooth',block:'start'})}
function closeEditor(){editor=null;stopEditorId=null;$('#routeEditor').hidden=true;$('#serviceRows').innerHTML='';$('#stopRows').innerHTML='';closeStopEditor()}
function renderEditor(){if(!editor)return;$('#routeEditorTitle').textContent=state.routes.some(r=>r.id===editor.id)?'Edytuj trasę':'Nowa trasa';$('#routeId').value=editor.id;$('#routeName').value=editor.name;$('#routeDescription').value=editor.description;$('#serviceRows').innerHTML=editor.services.map(s=>`<div class="serviceRow" data-service-id="${esc(s.id)}"><label class="field"><span>Godzina, na którą do pracy</span><button type="button" class="timeValueBtn serviceTargetTime" data-service-time="${esc(s.id)}">${esc(s.targetTime)}</button></label><button type="button" class="btn dangerText" data-remove-service="${esc(s.id)}">Usuń kurs</button></div>`).join('');$('#stopRows').innerHTML=editor.stops.map((s,i)=>stopHtml(s,i)).join('')}
function stopHtml(s,index){const times=editor.services.map(v=>`<td><button type="button" class="timeValueBtn stopTimeBtn" data-stop-time="${esc(s.id)}" data-service-id="${esc(v.id)}">${esc(normalizeTime(s.times[v.id]))}</button></td>`).join('');const heads=editor.services.map(v=>`<th>Na ${esc(v.targetTime)}</th>`).join('');return `<div class="stopCard" data-stop-id="${esc(s.id)}"><div class="stopTableWrap"><table class="routeTable"><thead><tr><th>#</th><th>Przystanek</th><th>Lokalizacja TAM / POWRÓT</th>${heads}<th>Akcje</th></tr></thead><tbody><tr><td>${index+1}</td><td><div style="display:flex;gap:6px;align-items:stretch"><button type="button" class="btn stopNameOpen" data-edit-stop="${esc(s.id)}" style="flex:1;text-align:left;white-space:normal">${esc(s.name||'Dodaj nazwę przystanku')}</button><button type="button" class="iconBtn dangerText" data-remove-stop="${esc(s.id)}" aria-label="Usuń przystanek" title="Usuń przystanek" style="flex:0 0 auto">✕</button></div></td><td><div class="locationCell"><span class="locationLabel">TAM</span><input class="locationOut" data-stop-out="${esc(s.id)}" value="${esc(s.locationOut)}"><button type="button" class="btn stopMap" data-map-field="locationOut">📍 Mapa</button></div><div class="locationCell locationReturnStack"><span class="locationLabel">POWRÓT</span><input class="locationReturn" data-stop-return="${esc(s.id)}" value="${esc(s.locationReturn)}"><button type="button" class="btn stopMap" data-map-field="locationReturn">📍 Mapa</button></div></td>${times}<td><div class="tableActions"><button type="button" class="iconBtn" data-move-up="${esc(s.id)}">↑</button><button type="button" class="iconBtn" data-move-down="${esc(s.id)}">↓</button></div></td></tr></tbody></table></div><button type="button" class="btn" data-add-stop-after="${esc(s.id)}">+ Dodaj przystanek</button></div>`}

function ensureStopEditor(){if($('#stopEditorModal'))return;const modal=document.createElement('div');modal.id='stopEditorModal';modal.className='modal';modal.hidden=true;modal.innerHTML=`<div class="modalCard" style="width:min(94vw,760px);max-width:760px;max-height:88vh;overflow:auto"><h3>Edytuj przystanek</h3><div id="stopEditorFields"></div><div class="actions"><button type="button" id="stopEditorSave" class="btn primary">Zapisz przystanek</button><button type="button" id="stopEditorCancel" class="btn">Anuluj</button></div></div>`;document.body.appendChild(modal)}
function openStopEditor(id){const s=stopById(id);if(!s)return;ensureStopEditor();stopEditorId=id;const rows=editor.services.map(v=>`<label class="field"><span>Godzina dla kursu na ${esc(v.targetTime)}</span><input class="stopEditorTime" data-service-id="${esc(v.id)}" type="time" value="${esc(normalizeTime(s.times[v.id]))}" style="font-size:18px"></label>`).join('');$('#stopEditorFields').innerHTML=`<div class="formGrid" style="grid-template-columns:1fr"><label class="field"><span>Nazwa przystanku</span><textarea id="stopEditorName" rows="3" style="width:100%;box-sizing:border-box;resize:vertical;min-height:90px;padding:12px;font:inherit;font-size:18px;line-height:1.4">${esc(s.name)}</textarea></label><label class="field"><span>Lokalizacja TAM</span><textarea id="stopEditorOut" rows="2" style="width:100%;box-sizing:border-box;resize:vertical;padding:12px;font:inherit">${esc(s.locationOut)}</textarea></label><label class="field"><span>Lokalizacja POWRÓT</span><textarea id="stopEditorReturn" rows="2" style="width:100%;box-sizing:border-box;resize:vertical;padding:12px;font:inherit">${esc(s.locationReturn)}</textarea></label></div><h4 style="margin:18px 0 10px">Godziny na przystanku</h4><div class="formGrid">${rows}</div>`;$('#stopEditorModal').hidden=false;requestAnimationFrame(()=>$('#stopEditorName')?.focus())}
function closeStopEditor(){const m=$('#stopEditorModal');if(m)m.hidden=true;stopEditorId=null}
function saveStopEditor(){const s=stopById(stopEditorId);if(!s)return closeStopEditor();const oldOut=s.locationOut;s.name=$('#stopEditorName').value.trim();s.locationOut=$('#stopEditorOut').value.trim()||DEFAULT_LOCATION;const ret=$('#stopEditorReturn').value.trim();s.locationReturn=(!ret||ret===oldOut)?s.locationOut:ret;$$('#stopEditorFields .stopEditorTime').forEach(i=>s.times[i.dataset.serviceId]=normalizeTime(i.value));closeStopEditor();renderEditor()}

function addService(){if(!editor)return;editor.services.push({id:makeId('service'),targetTime:'06:00'});renderEditor()}
function removeService(id){if(!editor)return;editor.services=editor.services.filter(s=>s.id!==id);editor.stops.forEach(s=>delete s.times[id]);renderEditor()}
function addStopAfter(id){if(!editor)return;const i=editor.stops.findIndex(s=>s.id===id);editor.stops.splice(i+1,0,normalizeStop({}));renderEditor();openStopEditor(editor.stops[i+1].id)}
function removeStop(id){if(!editor)return;const s=stopById(id);if(!s)return;const label=s.name||'ten przystanek';if(!confirm(`Czy na pewno usunąć przystanek „${label}”?`))return;if(editor.stops.length===1)editor.stops=[normalizeStop({})];else editor.stops=editor.stops.filter(x=>x.id!==id);renderEditor()}
function moveStop(id,delta){if(!editor)return;const i=editor.stops.findIndex(s=>s.id===id),j=i+delta;if(i<0||j<0||j>=editor.stops.length)return;[editor.stops[i],editor.stops[j]]=[editor.stops[j],editor.stops[i]];renderEditor()}
function validateEditor(){if(!editor.name.trim())return 'Podaj nazwę trasy.';if(!editor.services.length)return 'Dodaj co najmniej jeden kurs.';if(editor.stops.length<2)return 'Dodaj co najmniej dwa przystanki.';if(editor.stops.some(s=>!s.name.trim()))return 'Każdy przystanek musi mieć nazwę.';return ''}
function showNotice(text,error=false){let n=$('#routeSaveMessage');if(!n){n=document.createElement('div');n.id='routeSaveMessage';n.className='notice';$('#routeForm').prepend(n)}n.hidden=false;n.textContent=text;n.style.fontWeight='700';n.style.background=error?'#fff1f0':'#ecfdf3';n.style.color=error?'#8a1c13':'#116329';n.style.borderColor=error?'#b42318':'#16803c';n.scrollIntoView({behavior:'smooth',block:'nearest'})}
function saveRoute(){if(!editor)return;const err=validateEditor();if(err){showNotice(err,true);return}const i=state.routes.findIndex(r=>r.id===editor.id);if(i>=0)state.routes[i]=clone(editor);else state.routes.push(clone(editor));writeDraft();renderAll();showNotice(`Trasa „${editor.name}” została zapisana.`);setTimeout(()=>{closeEditor();show('routes')},450)}
function backupRoutes(){const routes=clone(state.routes);if(editor?.name.trim()){const i=routes.findIndex(r=>r.id===editor.id);if(i>=0)routes[i]=clone(editor);else routes.push(clone(editor))}return routes}
function saveData(){const d=new Date(),p=n=>String(n).padStart(2,'0');const name=`Kursy-kopia-danych-${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}.json`;const blob=new Blob([JSON.stringify({schemaVersion:1,routes:backupRoutes()},null,2)+'\n'],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function loadDataFile(file){try{const parsed=JSON.parse(await file.text());const routes=Array.isArray(parsed)?parsed:Array.isArray(parsed?.routes)?parsed.routes:null;if(!routes)throw new Error('Plik nie zawiera listy tras.');if(!confirm(`Wczytać ${routes.length} tras? Obecne dane lokalne zostaną zastąpione.`))return;state.routes=routes.map(normalizeRoute);writeDraft();closeEditor();renderAll();show('routes');alert(`Wczytano ${state.routes.length} tras.`)}catch(e){alert(`Nie udało się wczytać danych: ${e.message||e}`)}}
function resetRoutes(){if(!confirm('Usunąć lokalne zmiany i przywrócić dane z repozytorium?'))return;localStorage.removeItem(DRAFT_KEY);state.routes=clone(state.repoRoutes);closeEditor();$('#draftNotice').hidden=true;$('#dataStatus').textContent='Repozytorium';renderAll()}

function wheelMarkup(type,values,current){const copies=5;return `<div class="wheelColumn" data-wheel="${type}"><div class="wheelPad"></div>${Array.from({length:copies},(_,c)=>values.map(v=>`<button type="button" class="wheelOption ${v===current?'selected':''}" data-value="${v}" data-cycle="${c}">${v}</button>`).join('')).join('')}<div class="wheelPad"></div></div>`}
function setupWheel(type,current){const wheel=$(`[data-wheel="${type}"]`),mid=2;let timer;const opts=[...wheel.querySelectorAll('.wheelOption')];const mark=v=>{wheel.dataset.value=v;opts.forEach(o=>o.classList.toggle('selected',o.dataset.value===v));const input=type==='hour'?$('#manualHour'):$('#manualMinute');if(input&&document.activeElement!==input)input.value=v};const center=o=>{if(o)wheel.scrollTop=o.offsetTop-(wheel.clientHeight-o.offsetHeight)/2};const middle=v=>opts.find(o=>o.dataset.value===v&&+o.dataset.cycle===mid);const settle=()=>{const c=wheel.scrollTop+wheel.clientHeight/2;let best=opts[0],dist=Infinity;opts.forEach(o=>{const d=Math.abs(o.offsetTop+o.offsetHeight/2-c);if(d<dist){dist=d;best=o}});mark(best.dataset.value);center(middle(best.dataset.value))};opts.forEach(o=>o.onclick=()=>{mark(o.dataset.value);center(middle(o.dataset.value))});wheel.addEventListener('scroll',()=>{clearTimeout(timer);timer=setTimeout(settle,80)},{passive:true});requestAnimationFrame(()=>{mark(current);center(middle(current))})}
function openTimePicker(target){timeTarget=target;const current=target.kind==='service'?editor.services.find(s=>s.id===target.serviceId)?.targetTime:stopById(target.stopId)?.times[target.serviceId];const [hh='00',mm='00']=normalizeTime(current).split(':');$('#modalHour').innerHTML=wheelMarkup('hour',HOURS,hh);$('#modalMinute').innerHTML=wheelMarkup('minute',MINUTES,mm);ensureManualInputs(hh,mm);$('#timePickerModal').hidden=false;setupWheel('hour',hh);setupWheel('minute',mm)}
function ensureManualInputs(hh,mm){let box=$('#manualTimeEntry');if(!box){box=document.createElement('div');box.id='manualTimeEntry';box.style.cssText='display:flex;gap:10px;align-items:end;justify-content:center;margin:8px 0 14px';box.innerHTML='<label style="display:grid;gap:4px;font-size:12px;font-weight:700;text-align:center">Godzina<input id="manualHour" inputmode="numeric" maxlength="2" style="width:74px;padding:10px;text-align:center;font-size:22px;border:1px solid #bbb;border-radius:10px"></label><span style="font-size:26px;padding-bottom:8px">:</span><label style="display:grid;gap:4px;font-size:12px;font-weight:700;text-align:center">Minuty<input id="manualMinute" inputmode="numeric" maxlength="2" style="width:74px;padding:10px;text-align:center;font-size:22px;border:1px solid #bbb;border-radius:10px"></label>';$('#timePickerModal .modalTimePicker').before(box)}$('#manualHour').value=hh;$('#manualMinute').value=mm}
function manualToWheel(input,type,max){let raw=input.value.replace(/\D/g,'').slice(0,2);input.value=raw;if(raw==='')return;const value=String(Math.min(max,+raw)).padStart(2,'0'),wheel=$(`[data-wheel="${type}"]`);if(!wheel)return;wheel.dataset.value=value;[...wheel.querySelectorAll('.wheelOption')].forEach(o=>o.classList.toggle('selected',o.dataset.value===value));const target=[...wheel.querySelectorAll('.wheelOption')].find(o=>o.dataset.value===value&&o.dataset.cycle==='2');if(target)wheel.scrollTop=target.offsetTop-(wheel.clientHeight-target.offsetHeight)/2}
function saveTime(){if(!timeTarget)return;const h=$('[data-wheel="hour"]')?.dataset.value||'00',m=$('[data-wheel="minute"]')?.dataset.value||'00',value=`${h}:${m}`;if(timeTarget.kind==='service'){const s=editor.services.find(x=>x.id===timeTarget.serviceId);if(s)s.targetTime=value}else{const s=stopById(timeTarget.stopId);if(s)s.times[timeTarget.serviceId]=value}$('#timePickerModal').hidden=true;timeTarget=null;renderEditor()}
function updateNetwork(){const on=navigator.onLine;$('#netState').textContent=on?'Online':'Offline';$('#netDot').classList.toggle('off',!on)}
function setupInstall(){if(matchMedia('(display-mode: standalone)').matches)return;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installBanner').hidden=false});$('#installBtn').onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installBanner').hidden=true}};$('#installClose').onclick=()=>$('#installBanner').hidden=true}

function bindEvents(){document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){show(nav.dataset.view);return}const go=e.target.closest('[data-go]');if(go){show(go.dataset.go);return}const edit=e.target.closest('[data-edit-route]');if(edit){openEditor(edit.dataset.editRoute);return}const del=e.target.closest('[data-delete-route]');if(del){const r=state.routes.find(x=>x.id===del.dataset.deleteRoute);if(r&&confirm(`Usunąć trasę „${r.name}”?`)){state.routes=state.routes.filter(x=>x.id!==r.id);writeDraft();renderAll()}return}if(e.target.closest('#addRouteBtn')){openEditor();return}if(e.target.closest('#addServiceBtn')){addService();return}const es=e.target.closest('[data-edit-stop]');if(es){openStopEditor(es.dataset.editStop);return}const rs=e.target.closest('[data-remove-service]');if(rs){removeService(rs.dataset.removeService);return}const as=e.target.closest('[data-add-stop-after]');if(as){addStopAfter(as.dataset.addStopAfter);return}const rm=e.target.closest('[data-remove-stop]');if(rm){removeStop(rm.dataset.removeStop);return}const up=e.target.closest('[data-move-up]');if(up){moveStop(up.dataset.moveUp,-1);return}const dn=e.target.closest('[data-move-down]');if(dn){moveStop(dn.dataset.moveDown,1);return}const st=e.target.closest('[data-stop-time]');if(st){openTimePicker({kind:'stop',stopId:st.dataset.stopTime,serviceId:st.dataset.serviceId});return}const sv=e.target.closest('[data-service-time]');if(sv){openTimePicker({kind:'service',serviceId:sv.dataset.serviceTime});return}if(e.target.closest('#stopEditorSave')){saveStopEditor();return}if(e.target.closest('#stopEditorCancel')){closeStopEditor();return}if(e.target.closest('#exportRoutesBtn')){saveData();return}if(e.target.closest('#importRoutesBtn')){$('#importRoutesFile').value='';$('#importRoutesFile').click();return}if(e.target.closest('#resetRoutesBtn')){resetRoutes();return}if(e.target.closest('#closeRouteEditor')||e.target.closest('#cancelRouteBtn')){closeEditor();return}if(e.target.closest('#timePickerSave')){saveTime();return}if(e.target.closest('#timePickerCancel')){$('#timePickerModal').hidden=true;timeTarget=null;return}});
  document.addEventListener('input',e=>{if(!editor)return;if(e.target.id==='routeName'){editor.name=e.target.value;return}if(e.target.id==='routeDescription'){editor.description=e.target.value;return}const out=e.target.closest('[data-stop-out]');if(out){const s=stopById(out.dataset.stopOut);const old=s.locationOut;s.locationOut=out.value.trim()||DEFAULT_LOCATION;if(!s.locationReturn||s.locationReturn===old)s.locationReturn=s.locationOut;return}const ret=e.target.closest('[data-stop-return]');if(ret){const s=stopById(ret.dataset.stopReturn);s.locationReturn=ret.value.trim()||s.locationOut;return}if(e.target.id==='manualHour'){manualToWheel(e.target,'hour',23);return}if(e.target.id==='manualMinute'){manualToWheel(e.target,'minute',59);return}});
  $('#routeForm').addEventListener('submit',e=>{e.preventDefault();saveRoute()});$('#importRoutesFile').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)loadDataFile(f)});addEventListener('online',updateNetwork);addEventListener('offline',updateNetwork)}

async function init(){bindEvents();updateNetwork();setupInstall();try{const data=await loadRepoData();state.company=data.company||null;state.repoRoutes=(data.routes||[]).map(normalizeRoute);state.courses=data.courses||[];const draft=readDraft();state.routes=draft||clone(state.repoRoutes);$('#draftNotice').hidden=!draft;$('#dataStatus').textContent=draft?'Wersja robocza':'Repozytorium';renderAll()}catch(e){$('#loadError').hidden=false;$('#loadError').textContent=e.message;$('#dataStatus').textContent='Błąd danych'}try{const api=await checkApi();$('#apiStatus').textContent=api.label}catch{$('#apiStatus').textContent='Brak odpowiedzi'}if('serviceWorker'in navigator){try{const reg=await navigator.serviceWorker.register('./sw.js');reg.update()}catch{}}}
init();
