import {loadRepoData} from './data.js';
import {checkApi} from './api.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DRAFT_ROUTES_KEY='kursy.routes.draft.v2';
const DEFAULT_STOP_LOCATION='Centrum Zielonej Góry, Zielona Góra';
const hours=Array.from({length:24},(_,i)=>String(i).padStart(2,'0'));
const minutes=Array.from({length:60},(_,i)=>String(i).padStart(2,'0'));
const WHEEL_COPIES=5;
let state={company:null,routes:[],repoRoutes:[],courses:[],activeCourse:null,activeStop:0};
let deferredInstallPrompt=null;
let timeTarget=null;

function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function clone(v){return JSON.parse(JSON.stringify(v))}
function makeId(prefix='id'){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`}
function routeById(id){return state.routes.find(r=>r.id===id)}
function show(name){$$('.view').forEach(v=>v.hidden=v.id!==`view-${name}`);$$('.nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageTitle').textContent={home:'Strona główna',driver:'Tryb kierowcy',routes:'Trasy',courses:'Kursy',admin:'Administracja'}[name]||'Kursy'}
function loadDraftRoutes(){try{const r=localStorage.getItem(DRAFT_ROUTES_KEY);return r?JSON.parse(r):null}catch{return null}}
function saveDraftRoutes(){localStorage.setItem(DRAFT_ROUTES_KEY,JSON.stringify(state.routes));$('#draftNotice').hidden=false;$('#dataStatus').textContent='Wersja robocza';renderAll()}
function clearDraftRoutes(){localStorage.removeItem(DRAFT_ROUTES_KEY);state.routes=clone(state.repoRoutes);$('#draftNotice').hidden=true;$('#dataStatus').textContent='Repozytorium';renderAll()}
function mapUrl(location){return location?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location)}`:''}
function renderAll(){renderHome();renderRoutes();renderCourses();renderDriver()}
function renderHome(){$('#companyName').textContent=state.company?.name||'—';$('#routesCount').textContent=state.routes.length;$('#coursesCount').textContent=state.courses.length}
function renderRoutes(){const box=$('#routesList');if(!state.routes.length){box.innerHTML='<div class="empty">Nie ma jeszcze żadnej trasy. Kliknij „Dodaj trasę”, aby utworzyć pierwszą.</div>';return}box.innerHTML=state.routes.map(r=>`<div class="item"><div><strong>${esc(r.name)}</strong><br><small>${(r.stops||[]).length} przystanków • ${(r.services||[]).length} kursów • ${esc(r.description||'Bez opisu')}</small></div><div class="itemActions"><button class="btn" data-edit-route="${esc(r.id)}">Edytuj</button><button class="btn dangerText" data-delete-route="${esc(r.id)}">Usuń</button></div></div>`).join('');$$('[data-edit-route]').forEach(b=>b.onclick=()=>openRouteEditor(b.dataset.editRoute));$$('[data-delete-route]').forEach(b=>b.onclick=()=>deleteRoute(b.dataset.deleteRoute))}
function effectiveCourses(){const generated=[];state.routes.forEach(r=>(r.services||[]).forEach(s=>generated.push({id:`${r.id}:${s.id}`,routeId:r.id,name:`${r.name} • ${s.targetTime}`,departure:s.targetTime,serviceId:s.id,targetTime:s.targetTime})));return state.courses.length?state.courses:generated}
function renderCourses(){const box=$('#coursesList'),courses=effectiveCourses();if(!courses.length){box.innerHTML='<div class="empty">Brak kursów. Dodaj godziny kursów podczas edycji trasy.</div>';return}box.innerHTML=courses.map(c=>{const r=routeById(c.routeId);return `<div class="item"><div><strong>${esc(c.name||r?.name||c.id)}</strong><br><small>Do pracy na ${esc(c.targetTime||c.departure||'—')} • ${esc(r?.name||'Brak trasy')}</small></div></div>`}).join('')}
function renderDriver(){const box=$('#driverCourses'),courses=effectiveCourses();if(!courses.length){box.innerHTML='<div class="empty">Brak kursów do realizacji.</div>';return}box.innerHTML=courses.map(c=>{const r=routeById(c.routeId);return `<div class="item"><div><strong>${esc(c.name||r?.name||c.id)}</strong><br><small>Do pracy na ${esc(c.targetTime||c.departure||'—')}</small></div><button class="btn primary" data-start="${esc(c.id)}">Otwórz</button></div>`}).join('');$$('[data-start]').forEach(b=>b.onclick=()=>startCourse(b.dataset.start))}
function startCourse(id){const c=effectiveCourses().find(x=>x.id===id);if(!c)return;state.activeCourse=c;state.activeStop=0;renderActiveCourse()}
function renderActiveCourse(){const wrap=$('#activeCourse');if(!state.activeCourse){wrap.hidden=true;return}const r=routeById(state.activeCourse.routeId),service=(r?.services||[]).find(s=>s.id===state.activeCourse.serviceId),stops=r?.stops||[];wrap.hidden=false;$('#activeCourseTitle').textContent=state.activeCourse.name||r?.name||state.activeCourse.id;$('#activeCourseMeta').textContent=`Do pracy na ${state.activeCourse.targetTime||state.activeCourse.departure||'—'} • ${r?.name||'Brak trasy'}`;$('#activeStops').innerHTML=stops.map((s,i)=>{const loc=s.locationOut||s.location||s.coordinates||DEFAULT_STOP_LOCATION;const t=s.times?.[service?.id]||s.time||'';return `<div class="driverStop ${i===state.activeStop?'active':''}"><div><strong>${i+1}. ${esc(s.name)}</strong>${t?`<div class="stopClock">🕒 ${esc(t)}</div>`:''}</div><a class="btn mapBtn" href="${mapUrl(loc)}" target="_blank" rel="noopener">📍 MAPA</a></div>`}).join('')||'<div class="empty">Ta trasa nie ma przystanków.</div>';$('#nextStopBtn').disabled=!stops.length||state.activeStop>=stops.length-1}

function serviceRow(service={}){const row=document.createElement('div');row.className='serviceRow';row.dataset.serviceId=service.id||makeId('service');row.innerHTML=`<label class="field"><span>Godzina, na którą do pracy</span><button type="button" class="timeValueBtn serviceTargetTime">${esc(service.targetTime||'06:00')}</button></label><button type="button" class="btn dangerText removeService">Usuń kurs</button>`;row.querySelector('.serviceTargetTime').onclick=e=>openTimePicker(e.currentTarget);row.querySelector('.removeService').onclick=()=>{row.remove();renderStopsTableFromEditor()};return row}
function addService(service={}){$('#serviceRows').appendChild(serviceRow(service));renderStopsTableFromEditor()}
function currentServicesFromEditor(){return [...$('#serviceRows').children].map(row=>({id:row.dataset.serviceId,targetTime:row.querySelector('.serviceTargetTime').textContent.trim()}))}

function normalizeStop(stop={}){const times={...(stop.times||{})};return {id:stop.id||makeId('stop'),name:stop.name||'',locationOut:stop.locationOut||stop.location||stop.coordinates||DEFAULT_STOP_LOCATION,locationReturn:stop.locationReturn||stop.returnLocation||DEFAULT_STOP_LOCATION,times}}
function stopCard(stop={}){const s=normalizeStop(stop),wrap=document.createElement('div');wrap.className='stopCard';wrap.dataset.stopId=s.id;wrap.dataset.stopData=JSON.stringify(s);return wrap}
function editorStops(){return [...$('#stopRows').children].map(card=>{try{return JSON.parse(card.dataset.stopData)}catch{return null}}).filter(Boolean)}
function syncCardFromTable(card){const data=JSON.parse(card.dataset.stopData);const row=card.querySelector('tr');if(!row)return;data.name=row.querySelector('.stopName').value.trim();data.locationOut=row.querySelector('.locationOut').value.trim()||DEFAULT_STOP_LOCATION;data.locationReturn=row.querySelector('.locationReturn').value.trim()||DEFAULT_STOP_LOCATION;row.querySelectorAll('[data-time-service]').forEach(btn=>data.times[btn.dataset.timeService]=btn.textContent.trim());card.dataset.stopData=JSON.stringify(data)}
function renderStopsTableFromEditor(){const services=currentServicesFromEditor(),stops=editorStops();$('#stopRows').innerHTML='';if(!stops.length)stops.push(normalizeStop({}));stops.forEach((s,index)=>$('#stopRows').appendChild(buildStopCard(s,index,services)))}
function buildStopCard(stop,index,services){const card=stopCard(stop),s=JSON.parse(card.dataset.stopData);const timeHeaders=services.map(v=>`<th>Do ${esc(v.targetTime)}</th>`).join('');const timeCells=services.map(v=>`<td><button type="button" class="timeValueBtn stopTimeBtn" data-time-service="${esc(v.id)}">${esc(s.times?.[v.id]||'00:00')}</button></td>`).join('');card.innerHTML=`<div class="stopTableWrap"><table class="routeTable"><thead><tr><th>#</th><th>Przystanek</th><th>Lokalizacja TAM</th><th>Lokalizacja POWRÓT</th>${timeHeaders}<th>Akcje</th></tr></thead><tbody><tr><td>${index+1}</td><td><input class="stopName" value="${esc(s.name)}" placeholder="Nazwa przystanku"></td><td><div class="locationCell"><input class="locationOut" value="${esc(s.locationOut)}"><button type="button" class="btn stopMap" data-map-field="locationOut">📍 Mapa</button></div></td><td><div class="locationCell"><input class="locationReturn" value="${esc(s.locationReturn)}"><button type="button" class="btn stopMap" data-map-field="locationReturn">📍 Mapa</button></div></td>${timeCells}<td><div class="tableActions"><button type="button" class="iconBtn" data-up>↑</button><button type="button" class="iconBtn" data-down>↓</button><button type="button" class="iconBtn dangerText" data-remove>✕</button></div></td></tr></tbody></table></div><button type="button" class="btn addStopBelow">+ Dodaj przystanek poniżej</button>`;
  card.querySelectorAll('input').forEach(i=>i.addEventListener('input',()=>syncCardFromTable(card)));
  card.querySelectorAll('.stopTimeBtn').forEach(b=>b.onclick=e=>{syncCardFromTable(card);openTimePicker(e.currentTarget,()=>syncCardFromTable(card))});
  card.querySelector('.addStopBelow').onclick=()=>{syncAllStopCards();const arr=editorStops(),idx=[...$('#stopRows').children].indexOf(card);arr.splice(idx+1,0,normalizeStop({}));renderStopsFromArray(arr)};
  card.querySelector('[data-remove]').onclick=()=>{syncAllStopCards();const arr=editorStops().filter(x=>x.id!==s.id);renderStopsFromArray(arr.length?arr:[normalizeStop({})])};
  card.querySelector('[data-up]').onclick=()=>{syncAllStopCards();const arr=editorStops(),idx=arr.findIndex(x=>x.id===s.id);if(idx>0){[arr[idx-1],arr[idx]]=[arr[idx],arr[idx-1]];renderStopsFromArray(arr)}};
  card.querySelector('[data-down]').onclick=()=>{syncAllStopCards();const arr=editorStops(),idx=arr.findIndex(x=>x.id===s.id);if(idx<arr.length-1){[arr[idx+1],arr[idx]]=[arr[idx],arr[idx+1]];renderStopsFromArray(arr)}};
  return card}
function syncAllStopCards(){$$('#stopRows .stopCard').forEach(syncCardFromTable)}
function renderStopsFromArray(arr){const services=currentServicesFromEditor();$('#stopRows').innerHTML='';arr.forEach((s,i)=>$('#stopRows').appendChild(buildStopCard(s,i,services)))}

function wheelHtml(type,values,current){const repeated=Array.from({length:WHEEL_COPIES},(_,cycle)=>values.map(v=>`<button type="button" class="wheelOption" data-value="${v}" data-cycle="${cycle}">${v}</button>`).join('')).join('');return `<div class="wheelColumn" data-wheel="${type}"><div class="wheelPad"></div>${repeated}<div class="wheelPad"></div></div>`}
function setupModalWheel(type,value){const wheel=$(`#timePickerModal [data-wheel="${type}"]`),hidden=$(`#timePickerModal [data-${type}-value]`),opts=[...wheel.querySelectorAll('.wheelOption')],mid=Math.floor(WHEEL_COPIES/2);let timer,recentering=false;const mark=v=>{hidden.value=v;opts.forEach(o=>o.classList.toggle('selected',o.dataset.value===v))};const center=o=>{if(o)wheel.scrollTop=o.offsetTop-(wheel.clientHeight-o.offsetHeight)/2};const middle=v=>opts.find(o=>o.dataset.value===v&&+o.dataset.cycle===mid);const settle=()=>{const c=wheel.scrollTop+wheel.clientHeight/2;let best=opts[0],d=Infinity;opts.forEach(o=>{const x=Math.abs(o.offsetTop+o.offsetHeight/2-c);if(x<d){d=x;best=o}});mark(best.dataset.value);if(+best.dataset.cycle<=1||+best.dataset.cycle>=WHEEL_COPIES-2){recentering=true;center(middle(best.dataset.value));requestAnimationFrame(()=>recentering=false)}else center(best)};opts.forEach(o=>o.onclick=()=>{mark(o.dataset.value);center(o)});wheel.onscroll=()=>{if(recentering)return;clearTimeout(timer);timer=setTimeout(settle,70)};requestAnimationFrame(()=>{mark(value);center(middle(value))})}
function openTimePicker(button,onSave){timeTarget={button,onSave};const [hh='00',mm='00']=button.textContent.trim().split(':');$('#modalHour').innerHTML=wheelHtml('hour',hours,hh);$('#modalMinute').innerHTML=wheelHtml('minute',minutes,mm);$('#timePickerModal').hidden=false;setupModalWheel('hour',hh);setupModalWheel('minute',mm)}
function closeTimePicker(){$('#timePickerModal').hidden=true;timeTarget=null}

function openRouteEditor(id=null){const r=id?routeById(id):null;$('#routeEditorTitle').textContent=r?'Edytuj trasę':'Nowa trasa';$('#routeId').value=r?.id||'';$('#routeName').value=r?.name||'';$('#routeDescription').value=r?.description||'';$('#serviceRows').innerHTML='';const services=r?.services?.length?r.services:[{id:makeId('service'),targetTime:'06:00'}];services.forEach(s=>$('#serviceRows').appendChild(serviceRow(s)));renderStopsFromArray(r?.stops?.length?r.stops:[normalizeStop({})]);$('#routeEditor').hidden=false;$('#routeEditor').scrollIntoView({behavior:'smooth',block:'start'})}
function closeRouteEditor(){$('#routeEditor').hidden=true;$('#routeForm').reset();$('#serviceRows').innerHTML='';$('#stopRows').innerHTML=''}
function saveRouteFromForm(e){e.preventDefault();syncAllStopCards();const name=$('#routeName').value.trim(),services=currentServicesFromEditor(),stops=editorStops();if(!name)return alert('Podaj nazwę trasy.');if(!services.length)return alert('Dodaj co najmniej jeden kurs.');if(stops.length<2)return alert('Trasa powinna mieć co najmniej dwa przystanki.');if(stops.some(s=>!s.name))return alert('Każdy przystanek musi mieć nazwę.');const id=$('#routeId').value||makeId('route'),route={id,name,description:$('#routeDescription').value.trim(),services,stops};const idx=state.routes.findIndex(r=>r.id===id);if(idx>=0)state.routes[idx]=route;else state.routes.push(route);saveDraftRoutes();closeRouteEditor()}
function deleteRoute(id){const r=routeById(id);if(r&&confirm(`Usunąć trasę „${r.name}”?`)){state.routes=state.routes.filter(x=>x.id!==id);saveDraftRoutes()}}
function exportRoutes(){const blob=new Blob([JSON.stringify(state.routes,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='routes.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function resetRoutes(){if(confirm('Usunąć lokalne zmiany i ponownie wczytać trasy z repozytorium?')){clearDraftRoutes();closeRouteEditor()}}
function isStandalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function setupInstall(){if(isStandalone())return;addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installBanner').hidden=false});addEventListener('appinstalled',()=>$('#installBanner').hidden=true);$('#installBtn').onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installBanner').hidden=true}else alert('Otwórz menu przeglądarki i wybierz „Zainstaluj aplikację” lub „Dodaj do ekranu głównego”.')};$('#installClose').onclick=()=>$('#installBanner').hidden=true;setTimeout(()=>$('#installBanner').hidden=false,1200)}
function updateNetwork(){const on=navigator.onLine;$('#netState').textContent=on?'Online':'Offline';$('#netDot').classList.toggle('off',!on)}

$('#nextStopBtn').onclick=()=>{state.activeStop++;renderActiveCourse()};$('#closeCourseBtn').onclick=()=>{state.activeCourse=null;renderActiveCourse()};
$('#timePickerSave').onclick=()=>{if(!timeTarget)return;const value=`${$('#modalHourValue').value}:${$('#modalMinuteValue').value}`;timeTarget.button.textContent=value;timeTarget.onSave?.();closeTimePicker()};$('#timePickerCancel').onclick=closeTimePicker;

async function init(){$$('.nav button[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#addRouteBtn').onclick=()=>openRouteEditor();$('#addServiceBtn').onclick=()=>addService({id:makeId('service'),targetTime:'06:00'});$('#closeRouteEditor').onclick=closeRouteEditor;$('#cancelRouteBtn').onclick=closeRouteEditor;$('#routeForm').addEventListener('submit',saveRouteFromForm);$('#exportRoutesBtn').onclick=exportRoutes;$('#resetRoutesBtn').onclick=resetRoutes;addEventListener('online',updateNetwork);addEventListener('offline',updateNetwork);updateNetwork();setupInstall();try{const data=await loadRepoData();state={...state,...data,repoRoutes:clone(data.routes||[])};const draft=loadDraftRoutes();if(Array.isArray(draft)){state.routes=draft;$('#draftNotice').hidden=false;$('#dataStatus').textContent='Wersja robocza'}else $('#dataStatus').textContent='Repozytorium';renderAll()}catch(err){$('#dataStatus').textContent='Błąd danych';$('#loadError').hidden=false;$('#loadError').textContent=err.message}const api=await checkApi();$('#apiStatus').textContent=api.label;if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.register('./sw.js');reg.update()}}
init();