import {addDriver,createCompany,effectiveStatus,endTrial,grantPaidLicense,releaseDevice,setBlocked,setLicense,TrialStatus,activateDriver} from './license-model.js';
import {getDeviceIdentity} from './device-identity.js';
import {loadStore,saveStore} from './license-store.js';
let store=loadStore(); const save=()=>saveStore(store); const current=()=>store.companies[0];
const status={trial_pending:'Oczekuje na trial',trial_active:'Trial aktywny',active:'Aktywna',expired:'Wygasła',blocked:'Zablokowana'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); const day=v=>v?new Date(v).toLocaleDateString('pl-PL'):'—';
const activationLink=d=>`${location.origin}${location.pathname}#activate=${encodeURIComponent(d.activationToken)}`;
function deviceRows(items,role){return items.length?items.map(d=>`<div class="licenseRow"><span>${esc(d.deviceId.slice(0,20))}…<small>${day(d.lastSeenAt||d.activatedAt)}</small></span><button class="btn dangerText" data-release="${role}:${esc(d.deviceId)}">Zwolnij</button></div>`).join(''):'<div class="empty">Brak urządzeń.</div>'}
function renderCompany(){const c=current(),l=c.license,p=document.querySelector('#companyLicensePanel');if(!p)return;p.innerHTML=`<h2>Firma i licencja</h2><p class="muted">Widok klienta. Produkcyjnie limity i status zwraca Apps Script.</p><div class="licenseSummary"><strong>${esc(c.name)}</strong><span class="licenseStatus">${status[effectiveStatus(c)]}</span><span>Trial: ${day(l.trialStartedAt)} – ${day(l.trialEndsAt)}</span></div><div class="licenseGrid"><section><h3>Kierowcy (${c.drivers.length}/${l.limits.drivers})</h3><button class="btn primary" id="addLicensedDriver">+ Dodaj kierowcę</button><div class="licenseList">${c.drivers.map(d=>`<div class="licenseRow"><span><strong>${esc(d.name)}</strong><small>${esc(d.phone)} · ${d.status}</small></span><button class="btn" data-copy="${esc(d.activationToken)}">Kopiuj link</button><a class="btn" href="sms:${encodeURIComponent(d.phone)}?body=${encodeURIComponent(activationLink(d))}">Wyślij SMS</a></div>`).join('')||'<div class="empty">Brak kierowców.</div>'}</div></section><section><h3>Urządzenia administratorów (${c.adminDevices.length}/${l.limits.adminDevices})</h3>${deviceRows(c.adminDevices,'admin')}<h3>Urządzenia kierowców (${c.driverDevices.length}/${l.limits.driverDevices})</h3>${deviceRows(c.driverDevices,'driver')}</section></div>`}
function renderOwner(){const root=document.querySelector('#ownerLicensePanel');root.innerHTML=`<main class="ownerContent"><header><h1>Dystrybucja licencji</h1><button class="btn" id="closeOwner">Wróć do aplikacji</button></header><button class="btn primary" id="newCompany">+ Dodaj firmę</button>${store.companies.map(c=>{const l=c.license;return `<section class="ownerCompany"><h2>${esc(c.name)}</h2><p>${esc(c.adminEmail||'brak e-maila')} · <strong>${status[effectiveStatus(c)]}</strong></p><div class="ownerFields">${[['trialDays','Trial (dni)',l.trialDays],['adminDevices','Limit adminów',l.limits.adminDevices],['drivers','Limit kierowców',l.limits.drivers],['driverDevices','Urządzenia kierowców',l.limits.driverDevices]].map(([k,t,v])=>`<label>${t}<input data-field="${k}" data-company="${c.id}" type="number" value="${v}"></label>`).join('')}</div><p>Trial: ${day(l.trialStartedAt)} – ${day(l.trialEndsAt)} · Płatna do: ${day(l.paidEndsAt)}</p><div class="actions"><button class="btn" data-owner="save:${c.id}">Zapisz limity</button><button class="btn" data-owner="extend:${c.id}">Przedłuż trial</button><button class="btn" data-owner="end:${c.id}">Zakończ trial</button><button class="btn primary" data-owner="paid:${c.id}">Nadaj licencję płatną</button><button class="btn dangerText" data-owner="block:${c.id}">${l.blocked?'Odblokuj':'Zablokuj'}</button></div><details><summary>Historia (${c.history.length})</summary>${c.history.slice().reverse().map(h=>`<div>${day(h.at)} — ${esc(h.type)}</div>`).join('')}</details></section>`}).join('')}</main>`}
function activate(){const token=new URLSearchParams(location.hash.slice(1)).get('activate');if(!token)return;const c=store.companies.find(x=>x.drivers.some(d=>d.activationToken===token)),d=c?.drivers.find(x=>x.activationToken===token);if(!c||!d)return alert('Nieprawidłowy link aktywacyjny.');try{activateDriver(c,d.id,getDeviceIdentity());save();location.hash='';alert('Kierowca został aktywowany.');renderCompany()}catch(e){alert(e.message)}}
document.addEventListener('click',e=>{if(e.target.id==='addLicensedDriver'){const name=prompt('Imię i nazwisko kierowcy:'),phone=prompt('Numer telefonu kierowcy:');try{if(name&&phone){addDriver(current(),{name,phone});save();renderCompany()}}catch(x){alert(x.message)}}const copy=e.target.closest('[data-copy]');if(copy){const d=current().drivers.find(x=>x.activationToken===copy.dataset.copy);navigator.clipboard?.writeText(activationLink(d));alert('Link aktywacyjny skopiowany.')}const rel=e.target.closest('[data-release]');if(rel){const [role,deviceId]=rel.dataset.release.split(':');releaseDevice(current(),role,deviceId);save();renderCompany()}if(e.target.id==='newCompany'){const name=prompt('Nazwa firmy:');if(name){store.companies.push(createCompany({name,adminEmail:prompt('E-mail administratora:')||''}));save();renderOwner()}}if(e.target.id==='closeOwner'){location.hash='';location.reload()}const a=e.target.closest('[data-owner]');if(a){const [op,id]=a.dataset.owner.split(':'),c=store.companies.find(x=>x.id===id),now=new Date(),num=k=>Number(document.querySelector(`[data-company="${id}"][data-field="${k}"]`).value);if(op==='save')setLicense(c,{trialDays:num('trialDays'),limits:{adminDevices:num('adminDevices'),drivers:num('drivers'),driverDevices:num('driverDevices')}});if(op==='extend')setLicense(c,{status:TrialStatus.ACTIVE,trialStartedAt:c.license.trialStartedAt||now.toISOString(),trialEndsAt:new Date(+now+c.license.trialDays*86400000).toISOString()});if(op==='end')endTrial(c);if(op==='paid'){const days=Number(prompt('Dni licencji płatnej:',365))||365;grantPaidLicense(c,new Date(+now+days*86400000).toISOString())}if(op==='block')setBlocked(c,!c.license.blocked);save();renderOwner()}});
if(location.hash==='#owner-licenses'){document.querySelector('.app').hidden=true;document.querySelector('#ownerLicensePanel').hidden=false;renderOwner()}else{renderCompany();activate()}
