import assert from 'node:assert/strict';import test from 'node:test';
import {addDriver,activateAdminDevice,activateDriver,createCompany,effectiveStatus,endTrial,grantPaidLicense,releaseDevice,setBlocked,TrialStatus} from '../js/license-model.js';
const t=new Date('2026-08-01T00:00:00Z'),dev=n=>({deviceId:`d${n}`,fingerprint:`f${n}`});
test('firma zaczyna w trial_pending, a konfiguracja i kierowca go nie uruchamiają',()=>{const c=createCompany({name:'A'});assert.equal(c.license.status,TrialStatus.PENDING);addDriver(c,{name:'Jan',phone:'+48111'});assert.equal(c.license.status,TrialStatus.PENDING)});
test('pierwsza aktywacja kierowcy uruchamia dokładnie jeden trial',()=>{const c=createCompany({name:'A',trialDays:7}),a=addDriver(c,{name:'Jan',phone:'1'});activateDriver(c,a.id,dev(1),{now:t});const start=c.license.trialStartedAt; a.phone='2';activateDriver(c,a.id,dev(1),{now:new Date(+t+1000)});assert.equal(c.license.trialStartedAt,start);assert.equal(c.license.status,TrialStatus.ACTIVE)});
test('zmiana e-maila administratora i kolejny kierowca nie tworzą triala',()=>{const c=createCompany({name:'A',adminEmail:'a@a'}),a=addDriver(c,{name:'A',phone:'1'});activateDriver(c,a.id,dev(1),{now:t});const start=c.license.trialStartedAt;c.adminEmail='b@b';const b=addDriver(c,{name:'B',phone:'2'});activateDriver(c,b.id,dev(2),{now:new Date(+t+1000)});assert.equal(c.license.trialStartedAt,start)});
test('domyślny limit trzech urządzeń administratora blokuje czwarte',()=>{const c=createCompany({name:'A'});[1,2,3].forEach(n=>activateAdminDevice(c,'a@a',dev(n)));assert.throws(()=>activateAdminDevice(c,'a@a',dev(4)),/limit/)});
test('limit urządzeń kierowców, zwolnienie i ponowna aktywacja',()=>{const c=createCompany({name:'A',limits:{driverDevices:1}}),a=addDriver(c,{name:'A',phone:'1'}),b=addDriver(c,{name:'B',phone:'2'});activateDriver(c,a.id,dev(1),{now:t});assert.throws(()=>activateDriver(c,b.id,dev(2),{now:t}),/limit/);releaseDevice(c,'driver','d1');activateDriver(c,b.id,dev(2),{now:t});assert.equal(c.driverDevices.length,1)});
test('wygaśnięcie, przedłużenie, płatna licencja, blokada i odblokowanie',()=>{const c=createCompany({name:'A',trialDays:1}),a=addDriver(c,{name:'A',phone:'1'});activateDriver(c,a.id,dev(1),{now:t});assert.equal(effectiveStatus(c,new Date(+t+2*86400000)),TrialStatus.EXPIRED);c.license.trialEndsAt=new Date(+t+3*86400000).toISOString();assert.equal(effectiveStatus(c,t),TrialStatus.ACTIVE);endTrial(c,t);assert.equal(effectiveStatus(c,t),TrialStatus.EXPIRED);grantPaidLicense(c,new Date(+t+10*86400000).toISOString(),t);assert.equal(effectiveStatus(c,t),TrialStatus.ACTIVE_LICENSE);setBlocked(c,true,t);assert.equal(effectiveStatus(c,t),TrialStatus.BLOCKED);setBlocked(c,false,t);assert.equal(effectiveStatus(c,t),TrialStatus.ACTIVE_LICENSE)});
